version: "3"
services:
  nerdrealm-minecraft:
    container_name: nerdrealm-minecraft
    restart: unless-stopped
    build:
      context: .
    environment:
      - VERSION=1.19
      - MC_MEMORY=8192
    volumes:
      - type: bind
        source: ./volume
        target: /home/minecraft
    ports:
      - "25565:25565"
      - "25575:25575"
